name: Continuous Integration

on: [push, pull_request]

jobs:
  buildAndTest:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint